name: tea_plant_vision
description: "Tea plant disease detection app"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  http: ^1.2.0
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  permission_handler: ^10.4.0
  device_info_plus: ^9.0.0
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.1
  path: ^1.8.3
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tea1.png
    - assets/tea2.png
    - assets/tea3.png
    - assets/tea4.jpg
    - assets/splashscreen.jpg
    - assets/gallery.png
    - assets/camera.png